company: "Simons Foundation"
position: "High Performannce Computing intern"
passionate_about: "creating quality software to solve real world problems"
skill_evidence: "extensive experience with machine learning and data processing, in both my job experience and personal projects"
email: "chaseuelt@gmail.com"
phone: "+1 971-222-7416"
website: "https://cueltschey.com"
github: "https://github.com/cueltschey"
